In [4]:
# Q1: Print Hello World! on screen
print("Hello World!")

Hello World!


In [1]:
def hello(): 
    return "Hello World!"

print(hello())

Hello World!


In [ ]:
# --> Function
# First you create the function. 
# Then you Call the function.  

In [57]:
# Q2: Store your name in a variable and print: My name is Khushal

name = "My name is Khushal"
print(name)

My name is Khushal


In [12]:
def greet(name, age):
    return f'Hello {name}, You age is {age}'

name = input("What is your name: ")
age = input("What is your age: ")

print(greet(name, age))

Hello Veenu, You age is 22


In [44]:
# Q3: Take two numbers and print their sum, difference, product, and division.

# Variable declaration 
num1 = 21
num2 = 22

# Calculating the sum
sum = num1 + num2
print(f"Sum: {sum}")

# Calculating the difference
diff = num1 - num2
print(f"Diff: {diff}")

# Calculating the product
prod = num1 * num2
print(f"Prod: {prod}")

# Calculating the division
div = num1 / num2
print(f"Div: {div:.2f}")

Sum: 43
Diff: -1
Prod: 462
Div: 0.95


In [ ]:
# Q4: Check if a number is even or odd. 
user_num = int(input("Enter a number: "))

if user_num % 2 == 0: 
    print(f'{user_num} is even.')
else: 
    print(f'{user_num} is odd.')

22 is even.


In [ ]:
def is_even(num):
    if num % 2 == 0: 
        return f'{num} is even!'
    else: 
        return f'{num} is odd!'

num = int(input("Enter a num: "))
print(is_even(num))

22 is even!


In [ ]:
# Q5: Find the largest of three numbers.

# Variable declaration 
num1 = int(input("Enter a number"))
num2 = int(input("Enter a number"))
num3 = int(input("Enter a number"))

# Conditional Logic
if num1 >= num2:
    print(f'{num1} is greater')

elif num2 >= num3:
    print(f'{num2} is greater')

else:
    print(f'{num3} is greater')

In [1]:
# Print numbers from 1 to 20 using a loop.
def one_to_twenty(): 
    for i in range(1, 21): 
        print(i)
        
one_to_twenty()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [16]:
# Count how many numbers between 1–100 are divisible by 7.
def divisible_by_7():
    for i in range(1,100):
        if i % 7 == 0:
            print(i)

divisible_by_7()    

7
14
21
28
35
42
49
56
63
70
77
84
91
98


In [ ]:
# Reverse a string (e.g., "python" → "nohtyp")
string = "python"
length = len(string)
lst = []

for i in range(length-1, -1, -1): 
    lst.append(string[i])

print("".join(lst))

nohtyp


In [ ]:
def revered_string(string): 
    length = len(string)
    lst = []

    for i in range(length-1, -1, -1): 
        lst.append(string[i])
    
    return "".join(lst)

string = input("Enter a string: ")
print(revered_string(string))

In [27]:
# Check if a word is a palindrome (reads same forwards and backwards).
string = "mom"
length = len(string)
lst = []

for i in range(length-1, -1, -1): 
    lst.append(string[i])

new_string = "".join(lst)

if new_string == string: 
    print(f'{string} is palindrome')
else: 
    print(f'{string} is not palindrome')

mom is palindrome


In [45]:
# Create a list of 5 numbers and print the sum and average without using sum().
lst = [1, 2, 3, 4, 5]
_sum = 0
_avg = 0 

for i in lst: 
    _sum += i
    _avg = _sum / len(lst)

print(f'Sum: {_sum} \nAvg: {_avg}')

Sum: 15 
Avg: 3.0


In [2]:
import numpy as np

In [5]:
array = np.array([1, 2, 3, 4])
array

array([1, 2, 3, 4])

In [9]:
matrices = np.array([[1, 2, 3], [4, 5, 6]])
matrices

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
tenser = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tenser

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# d.type
np.array([1, 2, 0, 3, 4], dtype=float)
np.array([1, 2, 0, 3, 4], dtype=bool)

array([ True,  True, False,  True,  True])

In [29]:
# np.arange
np.arange(1, 11)
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [47]:
# reshape 
np.arange(1, 11).reshape(2, 5)
np.arange(1, 13).reshape(6, 2)
np.arange(1, 13).reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
# np.ones and np.zeros
np.ones((3, 4))
np.ones((4, 3))

np.zeros((4, 2))
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [124]:
# np.random
np.random.random((3, 4))
np.array(np.random.random((4, 3)) * 100, dtype = int)

array([[59, 47,  8],
       [73, 21, 72],
       [31, 67, 34],
       [46, 45, 28]])

In [129]:
# np.linspace 
np.linspace(1, 50, 10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [136]:
# np.identity 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Numpy Attributes

In [142]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape((3, 4))
a3 = np.arange(8).reshape(2, 2, 2)

In [154]:
# ndim
a1.ndim
a2.ndim
a3.ndim

3

In [157]:
# shape
a2.shape
a3.shape
a1.shape

(10,)