**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.0

In [ ]:
a = np.nan * np.empty(10)
a[4] = 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [9]:
a, b = map(int, input("Enter a number: ").split())

# arr = np.random.random((a,b))
arr1 = np.random.randint(1, 22, (a, b))
print(arr1)
print(f'Average: {arr1.mean()}')

[[ 9 16  2 10]
 [15 10 17  6]
 [ 1  5  2  2]
 [11 21 10 16]]
Average: 9.5625


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [8]:
def border_array(n1, n2): 
    arr = np.ones((n1, n2))
    arr[1:-1, 1:-1] = 0
    return arr
border_array(4, 4)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
# solution with random
arr2 = np.random.random(10)
arr2

array([0.37737885, 0.03607997, 0.24172891, 0.66354726, 0.52547418,
       0.24237858, 0.96263575, 0.02795302, 0.14771207, 0.82824388])

In [ ]:
# solution with linspace
np.linspace(0, 1, 12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [58]:
# This is general way of creating identity matrix. However this is not that much flexible.
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
# Here is the real solution of that question and more flexible approach for creating identity matrix. 
np.eye(3)
np.eye(3, 4)
np.eye(3, 4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [99]:
arr = np.zeros((5, 5))
arr += np.arange(5)
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [129]:
arr = np.random.randint(1, 100, (10, 2))
point = np.array([2, 3])

np.sqrt(np.sum((arr-point)**2, axis=1)).astype(int)

array([ 23,  76,  84,  66,  68,  78,  83,  82, 114, 125])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [3]:
# arr = np.zeros((6, 7, 8))
# print(arr)

np.unravel_index(100, (6, 7, 8)) 

(np.int64(1), np.int64(5), np.int64(4))

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
# np.array([1, 2, 3, 4, -8, -10], dtype=float)[::-1]

a = input("Enter space separated number: ").strip().split()
np.array(a, dtype=np.float16)[::-1]

['2', '3', '4', '5', '6']


array([6., 5., 4., 3., 2.], dtype=float16)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [30]:
arr = np.array([1, 2])
elements_count = arr.size
print(f'Array: {arr} \nElements_count: {elements_count}')

Array: [1 2] 
Elements_count: 2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Requires Numpy Array")
    elif arr.ndim > 1:
        raise TypeError("Requires 1D Array")
        
    return np.exp(arr)/np.sum(np.exp(arr))

softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
def vertical_stacking(*args):
    for i in args: 
        if type(i) != np.ndarray:
            raise TypeError("Requires numpy array!")
    
    return np.vstack(args)

arr1 = np.random.random((2, 6))
arr2 = np.random.randint(1, 100, (4, 6))
arr3 = np.random.randint(1, 100, (4, 6))

vertical_stacking(np.array(arr1), np.array(arr2), np.array(arr3))

array([[5.66234468e-01, 6.11520120e-01, 9.84584833e-01, 9.26622401e-01,
        3.48369551e-01, 2.80219621e-02],
       [1.96079525e-01, 4.28102187e-01, 2.38321256e-02, 1.34761117e-01,
        3.43899807e-01, 6.00906675e-01],
       [1.00000000e+01, 7.30000000e+01, 2.80000000e+01, 9.90000000e+01,
        2.20000000e+01, 5.00000000e+00],
       [3.30000000e+01, 5.90000000e+01, 1.90000000e+01, 2.50000000e+01,
        4.20000000e+01, 3.50000000e+01],
       [4.00000000e+01, 5.60000000e+01, 5.90000000e+01, 4.10000000e+01,
        6.20000000e+01, 2.90000000e+01],
       [7.60000000e+01, 3.00000000e+00, 8.60000000e+01, 3.20000000e+01,
        9.00000000e+01, 5.70000000e+01],
       [6.70000000e+01, 1.80000000e+01, 6.10000000e+01, 3.30000000e+01,
        5.10000000e+01, 7.00000000e+01],
       [1.30000000e+01, 7.60000000e+01, 7.00000000e+01, 7.30000000e+01,
        8.30000000e+01, 9.80000000e+01],
       [8.00000000e+01, 6.00000000e+01, 5.90000000e+01, 9.30000000e+01,
        8.00000000e+01, 

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [28]:
def date_array(start: str, end: str): 
    if type(start) != str or type(end) != str:
        raise TypeError

    return np.arange(start, end, dtype='datetime64[D]')

date_array('2020-12-01', '2020-12-07')

array(['2020-12-01', '2020-12-02', '2020-12-03', '2020-12-04',
       '2020-12-05', '2020-12-06'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [31]:
arr = np.round(np.random.random((4, 3))*100).astype(int)
arr - np.mean(arr, axis=1, keepdims=True)

array([[ 24.        , -52.        ,  28.        ],
       [ 27.        ,   1.        , -28.        ],
       [-32.66666667,  23.33333333,   9.33333333],
       [  0.66666667, -31.33333333,  30.66666667]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
arr = np.arange(9).reshape(3, 3)
arr[:, [0, 2, 1]] # swapping the columns
arr[[0, 2, 1], :] # swapping the rows


array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
arr = np.arange(10)
arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [62]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2593, 9671, 9932, 7490, 8577],
       [1169, 8546, 3137, 3041, 8697],
       [ 361, 4611, 7117, 5373, 8200],
       [9602, 8184, 5254, 7141, 3626],
       [3098,  555, 6759, 9415, 8553],
       [5677, 3510, 3647, 4799, 9391],
       [1584, 4111,  568, 4065, 7904],
       [8783, 2206, 6853, 7150, 1337]], dtype=int32)

In [64]:
# Fetch every alternate column of array
arr1[:, ::2]

array([[2593, 9932, 8577],
       [1169, 3137, 8697],
       [ 361, 7117, 8200],
       [9602, 5254, 3626],
       [3098, 6759, 8553],
       [5677, 3647, 9391],
       [1584,  568, 7904],
       [8783, 6853, 1337]], dtype=int32)

In [65]:
# Normalize the given array
(arr1 - arr1.min()) / (arr1.max() - arr1.min())

array([[0.23320447, 0.97273012, 1.        , 0.74485425, 0.8584265 ],
       [0.08442169, 0.85518755, 0.29004284, 0.28001254, 0.87096437],
       [0.        , 0.44404973, 0.70588235, 0.52366524, 0.81903667],
       [0.96552084, 0.81736496, 0.51123185, 0.70838993, 0.34113468],
       [0.28596803, 0.02026956, 0.66847769, 0.94598266, 0.85591892],
       [0.55542785, 0.32901473, 0.34332881, 0.4636924 , 0.94347508],
       [0.12778184, 0.39180859, 0.02162783, 0.3870024 , 0.78810992],
       [0.87994985, 0.19276983, 0.67829903, 0.70933027, 0.10197472]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [66]:
def nthmax(arr, n): 
    if n > len(arr): 
        raise IndexError('n is way out of limit')

    arr.sort()
    return arr[-n]

nthmax(np.array([12, 34, 40, 7, 1, 0]), 2)

np.int64(34)

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [67]:
a = np.array([1, 2, 3])
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])