## NumPy

NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

#### Importing NumPy

In [9]:
import numpy as np

#### Array Creation

In [8]:
a = np.array([1, 2, 3]) # this is called vector
print(a)

[1 2 3]


In [7]:
# 2D array (Matrix)
b = np.array([[1,2,3], [4,5,6]]) # this is called matrix
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# 3D array (tensor)
c = np.array([[[1,2], [3, 4]],[[5, 6], [7, 8]]]) # this is called tensor
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#### Creation Methods

In [28]:
# dtype
np.array([1, 2, 3], dtype=float)
np.array([4, 5, 6], dtype=bool)
np.array([7, 8, 'hi'])
np.array([10, 11, 12], dtype=str)

array(['10', '11', '12'], dtype='<U2')

In [40]:
# arange
np.arange(1, 11)
np.arange(1, 11, 2)
np.arange(2, 11, 2) # this is even number series as well. 

array([ 2,  4,  6,  8, 10])

In [48]:
# reshape
np.arange(1, 11).reshape(5, 2)
np.arange(1, 11).reshape(2, 5)
np.arange(1, 13).reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# np.ones and np.zeros -: both are used in initializing
np.ones((3, 4))
np.zeros((5, 8))

array([1, 1])

In [155]:
# np.random
np.random.random((3, 4))
np.random.random((4, 3))*100
np.round(np.random.random((4, 3))*100)
rand_arr = (np.random.random((3, 3))*100).astype(np.int32)
rand_arr

array([[57, 15, 80],
       [46, 51, 60],
       [63, 78,  7]], dtype=int32)

In [96]:
# np.linspace -: If you are generating numbers from -10 to 10. So the numbers are generated on the equal distance
np.linspace(-10, 10, 10) 
np.linspace(-10, 10, 5)
np.linspace(-10, 10, 3)
np.linspace(-10, 10, 2)
np.linspace(-10, 10, 1)
np.linspace(11, 10, 10)


array([11.        , 10.88888889, 10.77777778, 10.66666667, 10.55555556,
       10.44444444, 10.33333333, 10.22222222, 10.11111111, 10.        ])

In [105]:
# identity -: It's a matrix which diagonals are 1 and others are 0 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Attributes

In [135]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

In [ ]:
# ndim -: It tell the dimension of array.
a1.ndim
a2.ndim
a3.ndim

3

In [ ]:
# shape -: It tells number of rows and columns.
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [129]:
# size -: It simple tell the size of array. 
a1.size
a2.size
a3.size

8

In [138]:
# itemsize -: It tells us how much size is occupied in memory
a1.itemsize
a2.itemsize
a3.itemsize

8

In [144]:
# dtype -: It tells what the type of array. 
a1.dtype
a2.dtype
a3.dtype

dtype('int64')

#### Changing DataType

In [145]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

#### Array Operations

In [168]:
# Defining the arrays
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

In [186]:
# Scaler Operations

# arithmetic
a1 * 2
a1 + 2
a1 - 2
a1 ** 2
a2 / 2

array([[ 6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5],
       [10. , 10.5, 11. , 11.5]])

In [192]:
# relational 
a2 > 15
a2 == 22

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [198]:
# Vector operations -: It means when you apply operation on 2 np.arrays. 

# arithmetic
a1 + a2
a1 ** a2
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

#### Array Methods

In [ ]:
# Defining Array
a1 = np.random.random((3, 3))
a1 = np.round(a1*100)
a1

array([[64., 90., 52.],
       [40., 84., 65.],
       [49., 33., 36.]])

In [213]:
# max | min | sum | prod
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)

# You can furthermore apply these operations on row/column base as well. 
# 0 -> col and 1 -> row
np.max(a1, axis=1)
np.min(a1, axis=1)
np.sum(a1, axis=1)
np.prod(a1, axis=1)

array([299520., 218400.,  58212.])

In [229]:
# mean | median | std | var
np.mean(a1)
np.mean(a1, axis=1) # row wise mean 
np.mean(a1, axis=1).astype(np.int32)

np.median(a1)
np.median(a1, axis=1) # row wise median

np.std(a1)
np.std(a1, axis=1) # row wise std

np.var(a1)
np.var(a1, axis=1) # row wise var

array([251.55555556, 324.66666667,  48.22222222])

In [231]:
# dot product -: For dot product the first array column and second array row have to be same for instance: (3, 4) and (4, 3) First array column 4 is equal to second array row 4 is same. 

a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)

np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [233]:
# log and exponents 
np.log(a1)
np.exp(a1)

array([[6.23514908e+27, 1.22040329e+39, 3.83100800e+22],
       [2.35385267e+17, 3.02507732e+36, 1.69488924e+28],
       [1.90734657e+21, 2.14643580e+14, 4.31123155e+15]])

#### Indexing & Slicing

In [289]:
# Defining array
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(27).reshape(3, 3, 3)

In [ ]:
print(a2)

a2[1, 2] 
a2[2, 3]
a2[1, 0]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


np.int64(4)

In [264]:
print(a3)

a3[1, 0, 1]
a3[0, 0, 0]
a3[0, 1, 1]
a3[0, 1, 0]
a3[0, 0, 1]
a3[1, 0, 0]
a3[1, 1, 0]
a3[1, 1, 1]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


np.int64(7)

In [290]:
# slicing
print(a2)

a2[0, :]
a2[0, 1:3]
a2[2, 2:]
a2[1:, 3]
a2[1:, 1]
a2[0:2, 0]
a2[:, 0]
a2[1, 1:3]
a2[1:, 2:][1, 0]
a2[::2, ::3]
a2[::2, 1::2]
a2[1, ::3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([4, 7])

In [303]:
print(a3)

a3[1]
a3[::2]
a3[0, 1]
a3[1,2,1]
a3[2,1:, 1:]
a3[::2, 0, ::2]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[ 0,  2],
       [18, 20]])

#### Iteration

In [306]:
for i in a1: 
    print(i)

0
1
2
3
4
5
6
7
8
9


In [318]:
for i in a2: 
    print(i) # it print one row

print('\n----------------\n')

for i in a2: 
    print(i[0]) # it print one column

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]

----------------

0
4
8


In [323]:
for i in a3: 
    print(i) # it print one 2D array
    print('\n---------------\n')

[[0 1 2]
 [3 4 5]
 [6 7 8]]

---------------

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

---------------

[[18 19 20]
 [21 22 23]
 [24 25 26]]

---------------



In [325]:
# There is function np.nditer(), it prints every single item.
for i in np.nditer(a3): 
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#### Reshaping

In [332]:
# Transpose
np.transpose(a2)
a2.T
np.transpose(a3)
a3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [347]:
# ravel -: convert n dimension array in 1 dimension array.
np.ravel(a2)
a2.ravel() 

np.ravel(a3)
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#### Stacking
    It's useful when you want to merge the different datasets.

In [360]:
# Defining Array
a4 = np.arange(12).reshape(3, 4)
a5 = np.arange(12, 24).reshape(3, 4)

In [363]:
# Horizontal Stacking
np.hstack((a4, a5))
np.hstack((a4, a5, a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [365]:
# Vertical Stacking 
np.vstack((a4, a5))
np.vstack((a4, a5, a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Splitting

In [ ]:
# Horizontal Splitting
np.hsplit(a4, 2) # division must be equal 

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# Vertical Splitting
np.vsplit(a5, 3)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])