#### np.sort

    Return a sorted copy of an array.

numpy.sort(a, axis=-1, kind=None, order=None, *, stable=None)

In [ ]:
import numpy as np

In [11]:
# Defining Array
a = np.random.randint(1, 100, 15)
a

array([94, 93, 58, 79, 65, 64, 42,  8, 78, 48, 71, 43, 71, 10,  4])

In [12]:
# Defining Array
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[85, 75, 16, 29],
       [40, 28,  1, 57],
       [88, 40, 71, 20],
       [ 1, 91, 64, 14],
       [78, 17, 83, 74],
       [68, 89, 41, 11]])

In [ ]:
# sorting
np.sort(a)
np.sort(a)[::-1] # Descending order


np.sort(b) # In default it's doing row wise sorting.
np.sort(b, axis=0) # Now it's column wise sorting.
np.sort(b)[::-1]
np.sort(b, axis=0)[::-1]

array([[88, 91, 83, 74],
       [85, 89, 71, 57],
       [78, 75, 64, 29],
       [68, 40, 41, 20],
       [40, 28, 16, 14],
       [ 1, 17,  1, 11]])

#### np.append
    The np.append() method appends values along the mentioned axis at the end of the array.

In [ ]:
# Append method on 1D array
np.append(a, 22)

array([94, 93, 58, 79, 65, 64, 42,  8, 78, 48, 71, 43, 71, 10,  4, 22])

In [61]:
# Append method on 2D array
np.append(b, 100) # If we do this kind of appending, it convert the array in 1d, and then append number 100. 

np.append(b, np.random.random((b.shape[0], 1)), axis=1)

array([[85.        , 75.        , 16.        , 29.        ,  0.70243277],
       [40.        , 28.        ,  1.        , 57.        ,  0.3037329 ],
       [88.        , 40.        , 71.        , 20.        ,  0.60540337],
       [ 1.        , 91.        , 64.        , 14.        ,  0.7460285 ],
       [78.        , 17.        , 83.        , 74.        ,  0.24804496],
       [68.        , 89.        , 41.        , 11.        ,  0.1609982 ]])

#### np.concatenate
    This function concatenate a sequence of array along an existing axis. 

In [67]:
# Defining Array
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [71]:
# Concatenation by column
np.concatenate((c, d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [73]:
# Concatenation by rows
np.concatenate((c, d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

#### np.unique
    With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [75]:
# Defining Array
e = np.array([1, 2, 3, 3, 3, 4, 5, 5, 5, 6, 6, 1, 5, 3, 2])
e

array([1, 2, 3, 3, 3, 4, 5, 5, 5, 6, 6, 1, 5, 3, 2])

In [ ]:
# Unique method
np.unique(e)

array([1, 2, 3, 4, 5, 6])

#### np.expend_dims
    With the help of np.expend_dims() method, we can get the expended dimension of an array. 

In [90]:
np.expand_dims(a, axis=0)
np.expand_dims(a, axis=0).shape

np.expand_dims(a, axis=1)
# np.expand_dims(a, axis=1).shape

array([[94],
       [93],
       [58],
       [79],
       [65],
       [64],
       [42],
       [ 8],
       [78],
       [48],
       [71],
       [43],
       [71],
       [10],
       [ 4]])

#### np.where
    The np.where() method returns the indices of elements in an input array where the given condition is satisfied.

In [ ]:
# array
a

array([94, 93, 58, 79, 65, 64, 42,  8, 78, 48, 71, 43, 71, 10,  4])

In [ ]:
# Find all the indices which are value grater than 50
np.where(a > 50)

array([94, 93, 58, 79, 65, 64, 78, 71, 71])

In [96]:
# Find all the values which are grater than 50
a[np.where(a > 50)]

array([94, 93, 58, 79, 65, 64, 78, 71, 71])

In [102]:
# Replace all values greater than 50 with 0
np.where(a > 50, 0, a)

array([ 0,  0,  0,  0,  0,  0, 42,  8,  0, 48,  0, 43,  0, 10,  4])

In [104]:
# Replace all even numbers with 0
np.where(a % 2 == 0, 0, a)

array([ 0, 93,  0, 79, 65,  0,  0,  0,  0,  0, 71, 43, 71,  0,  0])

#### np.argmax
    The np.argmax method return indices of the max element of the array in a particular axis.

In [ ]:
# 1D array
a

array([94, 93, 58, 79, 65, 64, 42,  8, 78, 48, 71, 43, 71, 10,  4])

In [109]:
# argmax method
np.argmax(a)

0

In [111]:
# 2D array 
b

array([[85, 75, 16, 29],
       [40, 28,  1, 57],
       [88, 40, 71, 20],
       [ 1, 91, 64, 14],
       [78, 17, 83, 74],
       [68, 89, 41, 11]])

In [113]:
# Here argmax returning row wise. 
np.argmax(b, axis=1)

array([0, 3, 0, 1, 2, 1], dtype=int64)

In [115]:
# Here argmax returning column wise. 
np.argmax(b, axis=0)

array([2, 3, 4, 4], dtype=int64)

In [120]:
# argmin -: opposite of argmax
np.argmin(a)

14

#### np.cumsum
    This method is used when we want to compute the cumulative sum of array elements over a given axis.

In [122]:
# 1D array
a

array([94, 93, 58, 79, 65, 64, 42,  8, 78, 48, 71, 43, 71, 10,  4])

In [ ]:
# Cumulative method on 1D array
np.cumsum(a)

array([ 94, 187, 245, 324, 389, 453, 495, 503, 581, 629, 700, 743, 814,
       824, 828])

In [127]:
# 2D array
b

array([[85, 75, 16, 29],
       [40, 28,  1, 57],
       [88, 40, 71, 20],
       [ 1, 91, 64, 14],
       [78, 17, 83, 74],
       [68, 89, 41, 11]])

In [132]:
# Cumulative method on 2D array
np.cumsum(b)
np.cumsum(b, axis=0)
np.cumsum(b, axis=1)

array([[ 85, 160, 176, 205],
       [ 40,  68,  69, 126],
       [ 88, 128, 199, 219],
       [  1,  92, 156, 170],
       [ 78,  95, 178, 252],
       [ 68, 157, 198, 209]])

In [134]:
# Cumulative Product 
np.cumprod(a)

array([         94,        8742,      507036,    40055844, -1691337436,
        -871413504,  2055338496,  -737161216, -1664000000,  1732378624,
       -1555169280,  1847197696, -1992949760,  1545338880,  1886388224])

#### np.percentile
    This method used to compute the nth percentile of the given data (array elements) along the specified axis. 

In [136]:
# Array
a

array([94, 93, 58, 79, 65, 64, 42,  8, 78, 48, 71, 43, 71, 10,  4])

In [148]:
# Percentile
np.percentile(a, 100)
np.percentile(a, 50)
np.percentile(a, 0)

4.0

#### np.histogram
    Numpy has a built-in np.histogram() method which represent the frequency of data distribution in the graphical form. 

In [150]:
# Array 
a

array([94, 93, 58, 79, 65, 64, 42,  8, 78, 48, 71, 43, 71, 10,  4])

In [155]:
np.histogram(a, bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

(array([2, 1, 0, 0, 3, 1, 2, 4, 0, 2], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

#### np.corrcoef
    Return pearson product-moment correlation coefficients.

In [161]:
# Defining Array
salary = np.random.randint(1000, 10000, 5)
experience = np.array([1, 2, 2, 4, 2])
print(salary)
print(experience)

[4890 9947 4643 9146 1508]
[1 2 2 4 2]


In [165]:
# Correlation Coefficient Method
np.corrcoef(experience, salary)

array([[1.       , 0.4822598],
       [0.4822598, 1.       ]])

#### np.isin
    With the help of np.isin() method we can see that one array having values are checked in a different numpy array having different elements with different sizes. 

In [174]:
# Array
a
items = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [176]:
# isin method
a[np.isin(a, items)]

b[np.isin(b, items)]

array([40, 40, 20])

#### np.flip 
    The np.flip() method reverses the order of array elements along the specified axis, preserving the shape of the array.

In [183]:
# Array
print(a)
print('---------------------------------------------------------------------------------------------------------------------')
print(b)

[94 93 58 79 65 64 42  8 78 48 71 43 71 10  4]
---------------------------------------------------------------------------------------------------------------------
[[85 75 16 29]
 [40 28  1 57]
 [88 40 71 20]
 [ 1 91 64 14]
 [78 17 83 74]
 [68 89 41 11]]


In [188]:
# Flip method
np.flip(a)

np.flip(b)
np.flip(b, axis=0)
np.flip(b, axis=1)

array([[29, 16, 75, 85],
       [57,  1, 28, 40],
       [20, 71, 40, 88],
       [14, 64, 91,  1],
       [74, 83, 17, 78],
       [11, 41, 89, 68]])

#### np.put
    * This method replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 
    
    * Put method make permanent changes or changes in main array. 

In [203]:
# Array
print(a)
print('---------------------------------------------------------------------------------------------------------------------')
print(b)

[94 22 58 79 65 64 42  8 78 48 30 43 32 10  4]
---------------------------------------------------------------------------------------------------------------------
[[12 80 94 60]
 [40 28  1 57]
 [88 40 71 20]
 [ 1 91 64 14]
 [78 17 83 74]
 [68 89 41 11]]


In [202]:
# Put method 
np.put(a,1,22)
np.put(a,[10, 12], [30, 32])

np.put(b, [0, 3], [94, 80])
np.put(b, [0, 3], [12, 60])

#### np.delete
    The numpy.delete() method returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [207]:
# Array
print(a)
print('---------------------------------------------------------------------------------------------------------------------')
print(b)

[94 22 58 79 65 64 42  8 78 48 30 43 32 10  4]
---------------------------------------------------------------------------------------------------------------------
[[12 80 94 60]
 [40 28  1 57]
 [88 40 71 20]
 [ 1 91 64 14]
 [78 17 83 74]
 [68 89 41 11]]


In [209]:
# Delete method
np.delete(a, 0)

np.delete(b, 0)

array([80, 94, 60, 40, 28,  1, 57, 88, 40, 71, 20,  1, 91, 64, 14, 78, 17,
       83, 74, 68, 89, 41, 11])

#### Set Functions
1. np.union (1d)
2. np.intersect (1d)
3. np.setdiff (1d)
4. np.setxor (1d)
5. np.in (1d)

In [215]:
s1 = np.array([1, 2, 3, 4, 5])
s2 = np.array([6, 7, 8, 9, 4])

print(s1)
print('---------------------------------------------------------------------------------------------------------------------')
print(s2)

[1 2 3 4 5]
---------------------------------------------------------------------------------------------------------------------
[6 7 8 9 4]


In [213]:
# Set methods
np.union1d(s1, s2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Return values which present in both
np.intersect1d(s1, s2)

array([4])

In [220]:
# Return values which are only in s1
np.setdiff1d(s1, s2)
np.setdiff1d(s2, s1)

array([6, 7, 8, 9])

In [222]:
# Remove the commons
np.setxor1d(s1, s2)

array([1, 2, 3, 5, 6, 7, 8, 9])

In [224]:
# Check if given values is present in set or not. 
np.in1d(s1, 4)

array([False, False, False,  True, False])

#### np.clip()
    This method is used to clip(limit) the values in an array.

In [226]:
# array
a

array([94, 22, 58, 79, 65, 64, 42,  8, 78, 48, 30, 43, 32, 10,  4])

In [227]:
np.clip(a, a_min=25, a_max=75)

array([75, 25, 58, 75, 65, 64, 42, 25, 75, 48, 30, 43, 32, 25, 25])